table dBaseProduct
	lineageTag: b50dd9f0-8f51-4a2d-98c9-97b636f4a199

	column ProductID
		dataType: string
		lineageTag: e65b79e8-5006-4c98-b981-0265c5dd37a1
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: a3205777-cf51-4960-9ccd-840f172c1a45
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 4f39f253-3e5e-4cc5-b540-69eafec9a441
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: 65cc2de8-7bc7-433b-ab13-8f48a3d861ce
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	partition dBaseProduct = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\ronildo\Desktop\workspace\pratice-bi-amazon\amazon_dataset\dBaseProduct.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductID", type text}, {"ProductName", type text}, {"Category", type text}, {"Brand", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

